on:
  push:
    branches: [ 2-compiling-and-making-binary-via-github-actions ]


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
   # Specify the environment to use its variables
    environment: release

    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18  # Use the version of Go your project requires

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Build
      run: |
        go build -v -o installer ./main.go
    - name: Test with Go
        run: go test -json > TestResults-${{ matrix.go-version }}.json
    - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          name: Go-results-${{ matrix.go-version }}
          path: TestResults-${{ matrix.go-version }}.json
    - name: Semantic Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npx semantic-release